name: Run Crawler

on:
  schedule:
    - cron: "0 * * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  crawler:
    runs-on: ubuntu-latest

    steps:
      - name: checkout latest code
        uses: actions/checkout@v2.3.4
      - name: setup node environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: '14'
          cache: 'yarn'
      - name: install dependencies
        run: yarn install          
      - name: begin crawler
        run: node start.js
        env:
          TYPESENSE_HOST: ${{ secrets.TYPESENSE_HOST }}
          TYPESENSE_PORT: ${{ secrets.TYPESENSE_PORT }}
          TYPESENSE_KEY: ${{ secrets.TYPESENSE_KEY }}
          TYPESENSE_PROTOCOL: ${{ secrets.TYPESENSE_PROTOCOL }}
